### ISSUE TITLE
Something not sent to slaves yet 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [radargun/radargun#254]
I am hitting this exception

07:37:22 java.lang.IllegalStateException: Something not sent to slaves yet: {java.nio.channels.SocketChannel[connected local=/10.0.0.74:2103 remote=/10.0.0.74:56234]=java.nio.HeapByteBuffer[pos=0 lim=59 cap=8192]}
07:37:22 	at org.radargun.RemoteSlaveConnection.clearBuffer(RemoteSlaveConnection.java:131)
07:37:22 	at org.radargun.RemoteSlaveConnection.runStage(RemoteSlaveConnection.java:158)
07:37:22 	at org.radargun.Master.executeDistStage(Master.java:236)
07:37:22 	at org.radargun.Master.executeStage(Master.java:144)
07:37:22 	at org.radargun.Master.run(Master.java:98)
07:37:22 	at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
07:37:22 04:37:22,259 WARN  [org.radargun.RemoteSlaveConnection] (main) Failed to send termination to slaves.
07:37:22 java.lang.IllegalStateException: Something not sent to slaves yet: {java.nio.channels.SocketChannel[connected local=/10.0.0.74:2103 remote=/10.0.0.74:56234]=java.nio.HeapByteBuffer[pos=0 lim=59 cap=8192]}
07:37:22 	at org.radargun.RemoteSlaveConnection.clearBuffer(RemoteSlaveConnection.java:131)
07:37:22 	at org.radargun.RemoteSlaveConnection.mcastObject(RemoteSlaveConnection.java:144)
07:37:22 	at org.radargun.RemoteSlaveConnection.release(RemoteSlaveConnection.java:252)
07:37:22 	at org.radargun.Master.run(Master.java:131)
07:37:22 	at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
07:37:22 04:37:22,260 INFO  [org.radargun.ShutDownHook] (Thread-0) Master process is being shutdown
07:37:22 Master 3383 finished with value 127

**Comment by rvansa** [comment]
Hi, that happens when one of the slaves exits while communicating with it. Could you look into the slave log and check exception thrown there?

**Comment by Danny-Hazelcast** [comment]
yes, its a java.lang.OutOfMemoryError: PermGen  on one of the slaves.

I am using large cluster iteration settings 

```
 <clusters>
      <scale from="2" to="12" inc="1">
         <cluster />
      </scale>
   </clusters>
```

and one of the cluster i am using, seems to cause the problem,  
i think i read xml comments notes about ignoring leaking, or something.

**Comment by rvansa** [comment]
That means that there is a memory leak in implementation of plugin you're testing (Hazelcast I suppose) that causes that the classloader used to load the plugin classes is not released. Then, after you load many times, you run out of PermGen.

Do you have any unfinished threads that fail to be killed? (ScenarioCleanupStage should log something about that). You can try to setup &lt;cleanup heap-dump-dir="/tmp" /&gt; (after &lt;scenario /&gt; and see if you get some dumps to analyze - when the heap dump is produced, there shouldn't be any reference to plugin-specific classes anymore.

I know this is somewhat cumbersome, I had hard time releasing everything from Infinispan, too. Therefore RG 3.0 will get rid of the classloading separation completely and slave JVMs will be restarted for each run. The changes are already integrated to master branch, if you'd prefer to try out those.

**Comment by Danny-Hazelcast** [comment]
Hazelcast is working ok. 
Its Coherence giving the problem  (i think i read xml comments notes about ignoring leaking, or something.)

JVM restart sounds like the best thing

Thanks.

**Comment by rvansa** [comment]
OK. Btw. if you get Coherence working in transactional mode, I'll gladly welcome such contribution. I was not able to get over some exceptions and in the end I've given up.
