### ISSUE TITLE
Replace Projections with actual lambdas

### ISSUE THREAD

**Issue by rvansa** [radargun/radargun#260]
Radargun 3.0 is Java 8+, therefore we can use lambdas from now on. Review where Projections is used and replace the uses with lambdas where appropriate.

@rmacor I cannot assign that to you since you don't have write permissions in Radargun, but this could be a nice introduction into lambdas for you, if you're interested.

**Comment by rmacor** [comment]
Thanks @rvansa, it looks interesting. I'm going to have a look at it when I'll have a chance.
