### ISSUE TITLE
Update the wiki on the usage of dist.sh

### ISSUE THREAD

**Issue by jmarkos** [radargun/radargun#269]
Hi @rvansa @mcimbora @alanfx, this is just a dump of the necessary steps I got from Radim on running the dist.sh script locally. Could be added to the wiki, either to the 5 minute tutorial, or as a separate page. (I don't  have the rights to edit the wiki, and Github doesn't support PR's for wiki.)

Title: Using the dist.sh script on a single machine (Fedora 22):

1. Create virtual interfaces (eth0 is some physical interface)
sudo ifconfig eth0:1 192.168.11.101 netmask 255.255.255.0
sudo ifconfig eth0:2 192.168.11.102 netmask 255.255.255.0
sudo ifconfig eth0:3 192.168.11.103 netmask 255.255.255.0
sudo ifconfig eth0:4 192.168.11.104 netmask 255.255.255.0
sudo ifconfig eth0:5 192.168.11.105 netmask 255.255.255.0
sudo ifconfig eth0:6 192.168.11.106 netmask 255.255.255.0
sudo ifconfig eth0:7 192.168.11.107 netmask 255.255.255.0
sudo ifconfig eth0:8 192.168.11.108 netmask 255.255.255.0
sudo ifconfig eth0:9 192.168.11.109 netmask 255.255.255.0

2. Make sshd listen on the new interfaces - add the following to /etc/ssh/sshd_config
ListenAddress 192.168.11.101
ListenAddress 192.168.11.102
ListenAddress 192.168.11.103
ListenAddress 192.168.11.104
ListenAddress 192.168.11.105
ListenAddress 192.168.11.106
ListenAddress 192.168.11.107
ListenAddress 192.168.11.108
ListenAddress 192.168.11.109

3. Create aliases - add the following to /etc/hosts
192.168.11.101          test1
192.168.11.102          test2
192.168.11.103          test3
192.168.11.104          test4
192.168.11.105          test5
192.168.11.106          test6
192.168.11.107          test7
192.168.11.108          test8
192.168.11.109          test9

4. Restart everything
sudo systemctl restart network
sudo systemctl restart sshd

5. If you don't have a passwordless ssh key, you will need to create one. Make sure you set an output file other than ~/.ssh/id_rsa, so as not to override your old key. Other than that, just hit enter.
ssh-keygen -t rsa

6. Test it
ssh -i --path to the passwordless key-- test1 echo "Interfaces set up"

7. Finally, run Radargun with the dist.sh script
sh bin/dist.sh -t -r 'ssh -q -o "StrictHostKeyChecking false" -i ~/.ssh/<passwordless_key>' test1 test2 test3

**Comment by rvansa** [comment]
Step 7 is not required - you should run dist.sh simply with test1 test2....

**Comment by mcimbora** [comment]
@jmarkos Integrated, thanks. Content is available at http://radargun.github.io/using_the_scripts.html
