### ISSUE TITLE
Incorrect expected slave count

### ISSUE THREAD

**Issue by vjuranek** [radargun/radargun#275]
In client-server mode RG fails to start as it waits for more servers in the cluster than actually configured. It seems it counts also client into cluster size, e.g. for this configuration
```
<cluster name="1client">
  <group name="server" size="2" />
  <group name="client" size="1" />
</cluster>
```
if expects cluster of size 3:
```
[org.radargun.stages.lifecycle.LifecycleHelper] (sc-main) Number of members=[slave1/clustered(local=true, coord=true), slave0/clustered(local=false, coord=false)] is not the one expected: 3

```

**Comment by alanfx** [comment]
Hey @vjuranek, in your benchmark, are you starting all of the services at once? (i.e. the clients and the servers?) I think it would work if you had two `service-start` elements that each had the `groups` property set:

`<service-start groups="server" />
<service-start groups="client" />`

But I agree that this isn't ideal either. I'm not sure I know of a way to handle this situation, and the one where you specify multiple groups.

`<service-start groups="server1,server2" />`

**Comment by vjuranek** [comment]
Thanks @alanfx 
```
<service-start groups="server"/>
<service-start groups="client"/>
```
seems to work and I'm fine with it. I originally thought that this was some unintended regression and I wanted to fix it. After your explanation I have no problem with it :smiley:

**Comment by alanfx** [comment]
It would be nicer if a single `<service-start/>` element would work correctly in all situations, but I think the stage would have to know about group memberships and service configurations to get this right in all situations. I'll try to think of a better solution, but I'm glad this works, @vjuranek!

**Comment by rvansa** [comment]
I am not sure if the current HotRod service would keep trying to connect if the clients were started too soon (before servers), so this is another risk when having single `<service-start />`

**Comment by alanfx** [comment]
Yeah, that's a good point, @rvansa. The ServiceStartStage code would have to know that the server service should be started prior to the client service. Service dependencies anyone?!
