### ISSUE TITLE
Namespaces for stages

### ISSUE THREAD

**Issue by rvansa** [radargun/radargun#286]
Currently, all stages are inserted into single XSD file, that means all of them are in single XML namespace. With move towards supporting multiple types of plugins (not just Caches, but also JPA implementors and possibly others). We should allow stages to declare their namespaces to prevent naming conflicts.

**Comment by mcimbora** [comment]
https://github.com/radargun/radargun/pull/305

**Comment by mcimbora** [comment]
Integrated
