### ISSUE TITLE
Document legacy test behaviour, throughput vs. latency

### ISSUE THREAD

**Issue by rvansa** [radargun/radargun#297]

**Comment by mcimbora** [comment]
https://github.com/radargun/radargun/wiki/Understanding-stress-test-results-in-RadarGun-2

**Comment by rvansa** [comment]
@mcimbora pls add the stage configuration with explicit puts/gets setting to get the picture what kind of stress you're running. And link that page to wiki home so it's easily accessible to end users.

**Comment by rvansa** [comment]
@mcimbora And please add documentation of percentiles charts, too.

Maybe a page with examples how to configure statistics would be useful, too.

**Comment by mgencur** [comment]
Throughtput vs. latency has been documented on Wiki. The new documentation will include this information as well.
