### ISSUE TITLE
Log tailing is broken on slaves

### ISSUE THREAD

**Issue by vjuranek** [radargun/radargun#314]
When log tail is turned on (with `-t` option) on slaves, it doesn't work any more and the output is stopped almost immediately, just after acquiring lock:
```
15:08:00,937 INFO  [org.radargun.RemoteMasterConnection] (main) Response successfully sent to the master
15:08:00,937 INFO  [org.radargun.ShutDownHook] (Thread-0) Slave process is being shutdown
15:08:00,999: Waiting for lock on file /tmp/restart-02360494704594478985.tmp
15:08:01,253: Lock acquired
```

**Comment by alanfx** [comment]
The issus is that the PID of the process changes when the slave processes are restarted, so the tailing stops. Removing the `--pid $SLAVE_PID` allows tailing the log file to work, but it no longer exits when the benchmark completes.

**Comment by vjuranek** [comment]
I tested the fix with Jenkins RadarGun plugin and everything seems to work fine - nice work @alanfx ! I guess we can close this issue (and eventually create new one if some issues appear in the future).

**Comment by alanfx** [comment]
Thanks, @vjuranek. I think there still might be some corner cases where the tail is not ended, but the logs should be complete at this point. I'm still considering changes to RadarGun to fix this more completely.

**Comment by alanfx** [comment]
There is definitely something wrong with the bash log tailer around the timeouts, so I am reopening this issue.

**Comment by alanfx** [comment]
https://github.com/radargun/radargun/pull/378

**Comment by alanfx** [comment]
Resolving this issue based on the PR above...unless I hear otherwise!
