### ISSUE TITLE
Wrong expected slave count when mixing clustered and non-clustered services

### ISSUE THREAD

**Issue by GhostInAMachine** [radargun/radargun#324]
Hi,

I want to create a benchmark that measures the performance of Hazelcast clients.

I have create a non-clustered Hazelcast client service and then set it up like this in XML file:

    <clusters>
        <cluster size="2">
            <group name="server" size="1" />
            <group name="client" size="1" />
        </cluster>
    </clusters>

    <scenario>
        <service-start />
        <jvm-monitor-start />
        <load-data groups="client" num-entries="5000"/>
    </scenario>

When launching the benchmark I observe the following message:

    Number of members=1 is not the one expected: 2

I am using 2.1.0.RELEASE version.

**Comment by mcimbora** [comment]
Hey, the solution is to start both groups separately, i.e.

    <service-start groups="server" />
    <service-start groups="client" />

**Comment by GhostInAMachine** [comment]
Thanks for the prompt response. 

I used file benchmark-cs.xml as a reference, it does not have this separate tags.

I just tried your suggestion and after successfully launching both of the services everything just hangs and does not proceed.

**Comment by mcimbora** [comment]
As a starting point, it'd be nice if you could provide:
1) benchmark configuration
2) master & slave logs

**Comment by vjuranek** [comment]
You can also provide stack traces from master and slave to have more precise idea where it got stuck (you can also compare with stack traces provided in #319 maybe you are hitting same issue)

**Comment by GhostInAMachine** [comment]
Apparently there was a problem with the plugin I wrote, so no problem here.
Thanks for the support.

**Comment by rvansa** [comment]
@GhostInAMachine Since you wrote a plugin for the client service (RG implements only embedded mode ATM), contributions are welcome.
