### ISSUE TITLE
RadarGun pages

### ISSUE THREAD

**Issue by rvansa** [radargun/radargun#325]
Nice & cool look? Documentation per version? Technology?

**Comment by rvansa** [comment]
I wouldn't mind if we had something better than github wiki pages, with documentation per version (probably in asciidoc?) and nice styles. However although I could find some time to write docs, I won't find time to play with graphics etc.
Also, I was teased about the logo I put up, so if you can create anything more sleek, contributions are welcome.

**Comment by mcimbora** [comment]
https://github.com/radargun/radargun/pull/328
