### ISSUE TITLE
RG 3.x build fails with jdg profile enabled

### ISSUE THREAD

**Issue by mcimbora** [radargun/radargun#329]
Builds fine with 2.x branch.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project plugin-jdg63: Compilation failure: Compilation failure:
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[17,7] error: cannot access Iterable
[ERROR] class file for org.radargun.traits.Iterable not found
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[23,82] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[23,17] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[31,71] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[31,92] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[31,20] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[56,60] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63EmbeddedService.java:[44,55] error: incompatible types: JDG63Iterable cannot be converted to InfinispanIterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[22,3] error: method does not override or implement a method from a supertype
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[24,10] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[24,9] error: illegal start of type
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[24,17] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[25,56] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[30,3] error: method does not override or implement a method from a supertype
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[32,10] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[32,9] error: illegal start of type
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[32,17] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[33,56] error: cannot find symbol
[ERROR] class JDG63Iterable
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[67,6] error: method does not override or implement a method from a supertype
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[72,6] error: method does not override or implement a method from a supertype
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[77,6] error: method does not override or implement a method from a supertype
[ERROR] /home/mcimbora/Projects/radar-gun/radargun/plugins/jdg63/src/main/java/org/radargun/service/JDG63Iterable.java:[82,6] error: method does not override or implement a method from a supertype

**Comment by rvansa** [comment]
Sounds like someone is about to set up full build in CI on each PR?

**Comment by mcimbora** [comment]
https://github.com/radargun/radargun/pull/332
