### ISSUE TITLE
Test Stages should fail immediately if getCache() fails or the Cache object is null

### ISSUE THREAD

**Issue by alanfx** [radargun/radargun#357]
While running some long term tests, I ran into this issue. There is no point in the test continuing, because every operation fails and the logs grow drastically. There are a couple of ways to fix this:

1. Checks for `null` could be added to the `getCache()` implementations
2. Checks for `null` could be added to the `Cache` constructor implementations
3. An `isValid()` method could be added to the `Cache` interface

I am leaning towards (1), because then an error message can include the name of the cache that could not be retrieved.

**Comment by rvansa** [comment]
I am ok with throwing an exception from the implementations of BasicOperations.getCache() if the cache does not exist and can't be created, if that's what you mean.

**Comment by alanfx** [comment]
@rvansa, yes that is an important distinction and the case for Infinispan server today. I need to check when asymmetric cache support was dropped, though. Thanks

**Comment by alanfx** [comment]
PR sent: https://github.com/radargun/radargun/pull/359
