### ISSUE TITLE
Verticalize results table

### ISSUE THREAD

**Issue by zhostasa** [radargun/radargun#392]
The results table tends to get quite wide with multiple iterations, it is requested to make it possible to search trough it only by scrolling.

**Comment by mgencur** [comment]
This is covered by https://github.com/radargun/radargun/pull/398

**Comment by mgencur** [comment]
@zhostasa , can this issue be closed? I think this was already implemented.

**Comment by zhostasa** [comment]
@mgencur Yeah, this can be closed

**Comment by mgencur** [comment]
Closing. Thanks.
