### ISSUE TITLE
Benchmark configuration file should be a part of the HTML report

### ISSUE THREAD

**Issue by rmacor** [radargun/radargun#421]
It would be useful to have configuration file attached to the HTML report, in the configuration section. (Next to Infinispan and JGroups configuration)

**Comment by rvansa** [comment]
Actually you could then replace the benchmark configuration section completely, but it would be nice if you could post the XML with nice syntax highlighting.

**Comment by mgencur** [comment]
@rvansa I was thinking about the same but then I realized that only the Scenario is right now in the configuration section and it is good to see immediately some of the parameters in the scenario. The whole configuration file could be quite long in some cases and could make the page too long. 
Anyway, I'd suggest moving the Scenario to the end of the page. We're usually more interested in the "timeline" charts. What about moving them before the scenario? I.e. have all charts available at the top and then have a description of the scenatio.

**Comment by alanfx** [comment]
You could also just copy the XML file into the HTML report directory and include a link to it in the report

**Comment by mgencur** [comment]
@rmacor , @rvansa , @alanfx 

IMO, the ideal structure of the report page could look like this:

- Tests
- Timelines (I'd like to rename it to something more intuitive, e.g. "Resource utilization", and also move these charts right after Tests, before configuration)
- Radargun configuration
     1) Link to RG benchmark
     2) Configurations  (let's keep it because we have clickable links to configs for servers etc.)
     3) Scenario (we can either keep it or remove it)

WDYT?

**Comment by rvansa** [comment]
@mgencur Timelines are for all data that aren't tied to one stage. E.g. some background stages that don't create a Test use these for reporting number of entries on each node. If you want to split that into "resources" and "others", go forward.

Change the order as you prefer, though if you want to spend more time on this, I think that tabbed interface would be even better.

**Comment by rvansa** [comment]
If you're about to include the XML into the report, you can use https://github.com/google/code-prettify to do the syntax highlighting.

**Comment by mgencur** [comment]
OK. Thanks for the tips. Regarding including XML, it's probably enough to put a link to an XML file there. WEB browsers have syntax highlighting for XML by default.

**Comment by alanfx** [comment]
@mgencur, I just want to be clear about the link to the XML benchmark file. Do you intend to copy the benchmark file into the results directory? I just want to make sure you aren't linking to the file outside the results directory, since it is bound to be changed!

**Comment by mgencur** [comment]
@alanfx , OK, I will make sure this link will remain functional and copy it to the results directory.

**Comment by alanfx** [comment]
Thanks, @mgencur. The only other issue I see with this approach is that it is possible to import the scenario from another file. In that case you'd either (a) lose the scenario or (b) have to parse the file and copy/include a second file.

**Comment by mgencur** [comment]
This has been implemented and is in upstream now.
