### ISSUE TITLE
Benchmark should fail if a stage refers to a group that doesn't exist

### ISSUE THREAD

**Issue by alanfx** [radargun/radargun#425]
hat tip to @mgencur for this one!

Martin sent me a benchmark configuration that was producing nothing in the reports. He defined this group at the top:

```
<group name="clients" size="1"/>
```

Then used that group to start the service:

```
<service-start groups="clients"/>
```

And loaded the cache:

```
<cache:load groups="clients" num-entries="1000" num-threads="10"/>
```

But then the test is run with group "client" which doesn't exist:

```
<l:basic-operations-test test-name="read-only-stress-test" duration="5m" num-threads-per-node="25" amend-test="true" put-ratio="0" get-ratio="5" iteration-property="num-threads-per-node" groups="client">
```

The benchmark runs to completion without any errors. If a stage is configured to run on a group that has not been defined, the benchmark should fail.

**Comment by mgencur** [comment]
This issues has been fixed. See #426
