### ISSUE TITLE
Enable getting slave addresses via properties

### ISSUE THREAD

**Issue by mgencur** [radargun/radargun#449]
Example:
When I have the following definition of clusters:
`<clusters>
      <cluster>
         <group name="servers" size="1"/>
         <group name="clients" size="1"/>
      </cluster>
   </clusters>
`

It should be possible to get slave's address via a property:
`<setup group="clients" plugin="resteasy-http">
     <rest-client-stateful xmlns="urn:radargun:plugins:resteasy-http:3.0">
           <servers>${group.servers.0}:8080</servers>
     </rest-client-stateful>
</setup>
`

**Comment by rvansa** [comment]
Hmm, regrettably the slaves addresses are unknown to both master and slave nodes. Configuration is evaluated on all slaves separately (and not at all on master), so you would have to check the addresses when all slaves connect, and post this to slaves in `Master` - or maybe rather add that into `o.r.config.Cluster`.

Another problem is that you can have multiple ifaces, and not always you want to use the same iface as for Slave - Master connection. As you can't discover the other ifaces from master automatically, that requires sending that info from Slave (probably using `RemoteMasterConnection.connectToMaster`).

As a last remark, RG already has convention for accessing element of a list and that is `#{ ${foo}.get(0) }`. Syntax would then be `${ #{ ${groups.servers}.get(0) }.eth2 }` - though I admit that this is rather cumbersome.
