### ISSUE TITLE
java.lang.NoSuchMethodError: org.jgroups.stack.ProtocolStack.insertProtocol(Lorg/jgroups/stack/Protocol;ILjava/lang/Class;)V

### ISSUE THREAD

**Issue by diegolovison** [radargun/radargun#514]
When running the tests against infinispan9x it is failing.

**Comment by vjuranek** [comment]
Done in bd6ebf1818f41ea760e5aae10328a99e6aac470f, I cherry-picked it also into master branch.

**Comment by alanfx** [comment]
Thank you, @vjuranek!
